### ISSUE TITLE
Don't change urls

### ISSUE THREAD

**Issue by glensc** [laminas/laminas-migration#47] opened 2020-06-20 12:03 UTC
Changing urls likely creates 404 urls

```diff
         // do our own header-body splitting.
         //
-        // \Zend\Mail\Storage\Message is unable to process mails that contain \n\n in text body
+        // \Laminas\Mail\Storage\Message is unable to process mails that contain \n\n in text body
         // because it has heuristic which headers separator to use
         // and that gets out of control
-        // https://github.com/zendframework/zend-mail/pull/159
+        // https://github.com/laminas/laminas-mail/pull/159
```

**Comment by weierophinney** [comment] 2020-06-23 15:35
This was an artifact from the original use case we tested on: migrating our own repositories!

I _think_ we can add rules around "github.com/zendframework/zend" and "github.com/zfcampus/zf" here, but will need to run some tests. (We've been avoiding using PCRE, as it uses dramatically more resources and time.)

**Comment by weierophinney** [comment] 2020-06-23 17:07
I created the following test case to reproduce the issue:

```php
namespace LaminasTest\Migration;

use Laminas\Migration\Helper;
use PHPUnit\Framework\TestCase;

class HelperTest extends TestCase
{
    public function zfGitHubUrlsToIgnoreDuringReplacements(): iterable
    {
        yield 'getexpressive.org'         => ['https://github.com/zendframework/getexpressive.org/pull/3'];
        yield 'zendframework.github.io'   => ['https://github.com/zendframework/zendframework.github.io/releases'];
        yield 'tutorials'                 => ['https://github.com/zendframework/tutorials/wiki'];
        yield 'component-split'           => ['https://github.com/zendframework/component-split/blob/master/README.md'];
        yield 'maintainers'               => ['https://github.com/zendframework/maintainers/blob/master/README.md'];
        yield 'modules.zendframework.com' => ['https://github.com/zendframework/modules.zendframework.com/wiki'];
        yield 'Namespacer'                => ['https://github.com/zendframework/Namespacer/blob/master/README.md'];
        yield 'subsplit-repos'            => ['https://github.com/zendframework/subsplit-ng/blob/master/README.md'];
        yield 'zendframework'             => ['https://github.com/zendframework/zendframework/blob/master/README.md'];
        yield 'Zend-components'           => ['https://github.com/zendframework/ZendAnything/blob/master/README.md'];
        yield 'zfbot'                     => ['https://github.com/zendframework/zfbot/blob/master/README.md'];
        yield 'ZFTool'                    => ['https://github.com/zendframework/ZFTool/blob/master/README.md'];
        yield 'zf-web'                    => ['https://github.com/zendframework/zf-web/projects'];
        yield 'zf1'                       => ['https://github.com/zendframework/zf1/projects']; // covers zf1-extras
        yield 'ZF2Package'                => ['https://github.com/zendframework/ZF2Package/projects'];
        yield 'zf3-web'                   => ['https://github.com/zendframework/zf3-web/projects'];
        yield 'components'                => ['https://github.com/zendframework/zend-anything/issue/not-for-real'];
        yield 'zf-components'             => ['https://github.com/zendframework/zf-anything/issue/not-for-real'];
        yield 'zf2-tutorial'              => ['https://github.com/zendframework/zf2-tutorial/issue/not-for-real'];
    }

    /**
     * @dataProvider zfGitHubUrlsToIgnoreDuringReplacements
     */
    public function testReplaceIgnoresZFGitHubUrls(string $url): void
    {
        $string = sprintf(
            'This text includes the url %s',
            $url
        );

        self::assertSame($string, Helper::replace($string));
    }
}
```

These each passed - the URLs were **not** rewritten.

Which version of laminas-migration are you using? which version of laminas-zendframework-bridge is in use? I suspect you might be on an older version, and that this issue is already addressed.

**Comment by glensc** [comment] 2020-06-25 08:21
I used `composer global install`, so it should be fresh version.

I don't have access right now to the laptop I ran the migration from, but I found that `--version` flag gives no useful info :D

```
➔ laminas-migration --version
laminas-migration

➔ which laminas-migration
/Users/glen/.composer/vendor/bin/laminas-migration
```

ps: there's [ocramius/package-versions][1] and [composer/package-versions-deprecated][2] packages which could solve the composer installed versions problem, and [composer 2.0 will have this built-in][3].

[1]: https://github.com/Ocramius/PackageVersions
[2]: https://github.com/composer/package-versions-deprecated
[3]: https://github.com/composer/composer/pull/8803

**Comment by weierophinney** [comment] 2021-01-05 17:07
Closing; unable to reproduce.

**Closed as completed by weierophinney** 2021-01-05 17:07 UTC
