### ISSUE TITLE
Class 'Laminas\Migration\DependencyPlugin' not found

### ISSUE THREAD

**Issue by glensc** [laminas/laminas-migration#38] opened 2020-03-02 13:17 UTC
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 1.0.3

#### Summary

Migration errors out with `Class 'Laminas\Migration\DependencyPlugin' not found` error.

#### Current behavior

```
$ bin/laminas-migration migrate

Migrating project at path "/Users/glen/scm/tmp/email-parse" to Laminas
======================================================================

Removing composer.lock
Removing configured vendor directory
PHP Fatal error:  Uncaught Error: Class 'Laminas\Migration\DependencyPlugin' not found in /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php:219
Stack trace:
#0 /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php(160): Laminas\Migration\Command\MigrateCommand->injectDependencyPlugin('/Users/glen/scm...', false, Object(Symfony\Component\Console\Style\SymfonyStyle))
#1 /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Command/Command.php(255): Laminas\Migration\Command\MigrateCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#2 /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Application.php(1001): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#3 /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Application.php(271): Symfony\Component\Console\Appl in /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php on line 219

Fatal error: Uncaught Error: Class 'Laminas\Migration\DependencyPlugin' not found in /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php on line 219

Error: Class 'Laminas\Migration\DependencyPlugin' not found in /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php on line 219

Call Stack:
    0.0003     370520   1. {main}() /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/bin/laminas-migration:0
    0.0110    1519944   2. Symfony\Component\Console\Application->run() /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/bin/laminas-migration:30
    0.0229    1855232   3. Symfony\Component\Console\Application->doRun() /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Application.php:147
    0.0231    1858640   4. Symfony\Component\Console\Application->doRunCommand() /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Application.php:271
    0.0231    1858640   5. Laminas\Migration\Command\MigrateCommand->run() /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Application.php:1001
    0.0233    1860392   6. Laminas\Migration\Command\MigrateCommand->execute() /Users/glen/scm/tmp/email-parse/vendor/symfony/console/Command/Command.php:255
    0.3946    1982488   7. Laminas\Migration\Command\MigrateCommand->injectDependencyPlugin() /Users/glen/scm/tmp/email-parse/vendor/laminas/laminas-migration/src/Command/MigrateCommand.php:160

[~/scm/tmp/email-parse (master)★] ➔
```

#### How to reproduce

```
$ git clone https://github.com/mmucklo/email-parse
$ composer require --dev laminas/laminas-migration
$ bin/laminas-migration migrate
```

#### Expected behavior

Anything else than the error.

**Comment by michalbundyra** [comment] 2020-03-02 13:20
Duplicate of #35 

Local installation of migration tool does not work right now. Probably we would need to remove this path completely. Please install globally and migrate you project.

https://docs.laminas.dev/migration/#via-a-global-composer-requirement

**Closed as completed** 2020-03-02 13:20 UTC
Labels: Duplicate
